source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='user_create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='user_change'),
    path('<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urls_api = [
    path('v1/', include('api_v1.urls')),
    path('v2/', include('api_v2.urls')),
    path('v3/', include('api_v3.urls'))
]

urlpatterns = [path('api/', include(urls_api))]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.views.generic import RedirectView
from webapp.views import IndexView, ArticleCreateView, ArticleView, ArticleUpdateView, ArticleDeleteView, \
    CommentCreateView, CommentUpdateView, CommentDeleteView, TestView, LikeArticleView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('articles/', RedirectView.as_view(pattern_name='webapp:index')),
    path('articles/add/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article_view'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update_view'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete_view'),
    path('article/<int:pk>/comment/add/', CommentCreateView.as_view(), name='comment_add'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update_view'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete_view'),
    path('test/', TestView.as_view(), name='test'),
    path('article/<int:pk>/like/', LikeArticleView.as_view(), name='article_like')
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinLengthValidator
from django.urls import reverse


class AbstractModel(models.Model):
    created_at = models.DateTimeField(verbose_name='Время создания', auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    class Meta:
        abstract = True


class Article(AbstractModel):
    title = models.CharField(max_length=50, null=False, blank=False, validators=[MinLengthValidator(4), ],
                             verbose_name="Заголовок")
    content = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Контент')
    author = models.ForeignKey(get_user_model(), default=1, related_name='articles', on_delete=models.CASCADE, verbose_name="Автор")
    tags = models.ManyToManyField('webapp.Tag', blank=True, related_name='articles', verbose_name='Теги')
    likes = models.ManyToManyField(get_user_model(), related_name='likes_articles')

    def __str__(self):
        return f'{self.id}. {self.title}'

    def get_absolute_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.pk})


class Comment(AbstractModel):
    article = models.ForeignKey('webapp.Article', related_name='comments', on_delete=models.CASCADE,
                                verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')

    author = models.ForeignKey(get_user_model(), default=1, related_name='comments', on_delete=models.CASCADE, verbose_name="Автор")

    def __str__(self):
        return self.text[:20]


class Tag(AbstractModel):
    name = models.CharField(max_length=31, verbose_name='Тег')

    def __str__(self):
        return self.name

source/webapp/forms.py
from django import forms
from webapp.models import Article, Comment
from django.utils.translation import gettext_lazy as _


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'tags', )
        widgets = {'tags': forms.CheckboxSelectMultiple}
        error_messages = {
            'title': {
                'required': _('Please enter'),
                'min_length': _('Заголовок слишком короткий')
            }
        }

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        if title == content:
            raise forms.ValidationError(_('Заголовок и Контент не могут быть одинаковые'))
        return cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label=_('Найти'))

source/webapp/views/article_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode

from django.db.models import Q
from webapp.models import Article
from webapp.forms import ArticleForm, SimpleSearchForm
from django.views.generic import View, FormView, ListView, DetailView, CreateView, UpdateView, DeleteView


class TestView(View):
    def get(self, request, *args, **kwargs):
        return JsonResponse([{'id': 1, 'name': 'test'}, {'id': 2, 'name': 'test2'}], safe=False)


class LikeArticleView(LoginRequiredMixin, View):
    # def get(self, request, pk, *args, **kwargs):
    #     article = get_object_or_404(Article, pk=pk)
    #     if request.user in article.likes.all():
    #         article.likes.remove(request.user)
    #     else:
    #         article.likes.add(request.user)
    #     return JsonResponse({'count': article.likes.count()}, safe=False)

    def post(self, request, pk, *args, **kwargs):
        article = get_object_or_404(Article, pk=pk)
        article.likes.add(request.user)
        return JsonResponse({'count': article.likes.count()}, safe=False)

    def delete(self, request, pk, *args, **kwargs):
        article = get_object_or_404(Article, pk=pk)
        article.likes.remove(request.user)
        return JsonResponse({'count': article.likes.count()}, safe=False)


class IndexView(ListView):
    model = Article
    template_name = 'articles/index.html'
    context_object_name = 'articles'
    paginate_by = 6
    paginate_orphans = 3
    ordering = ('-created_at',)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']
        return None

    def dispatch(self, request, *args, **kwargs):
        print(request.user)
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) |
                                       Q(content__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.search_form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search_value'] = self.search_value
        return context


class ArticleView(DetailView):
    model = Article
    template_name = 'articles/article_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.order_by('-created_at')
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'articles/article_create.html'
    model = Article
    # fields = ['title', 'content', 'author', 'tags']
    form_class = ArticleForm

    def form_valid(self, form):
        self.article = form.save(commit=False)
        self.article.author = self.request.user
        self.article.save()
        form.save_m2m()
        return redirect('webapp:article_view', pk=self.article.pk)

    # def get_success_url(self):
    #     return reverse('webapp:article_view', kwargs={'pk': self.object.pk})


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'articles/article_update.html'
    model = Article
    form_class = ArticleForm
    permission_required = 'webapp.change_article'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    # def dispatch(self, request, *args, **kwargs):
    #     self.article = self.get_object()
    #     return super().dispatch(request, *args, **kwargs)

    # def get_object(self):
    #     return get_object_or_404(Article, pk=self.kwargs.get('pk'))

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs['instance'] = self.article
    #     return kwargs

    # def form_valid(self, form):
    #     form.save()
    #     return redirect('webapp:article_view', pk=self.article.pk)


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'articles/article_delete.html'
    model = Article
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_article') or self.request.user == self.get_object().author
    # def get(self, request, *args, **kwargs):
    #     article = get_object_or_404(Article, pk=kwargs.get('pk'))
    #     return render(request, 'articles/article_delete.html', {'article': article})
    #
    # def post(self, request, *args, **kwargs):
    #     article = get_object_or_404(Article, pk=kwargs.get('pk'))
    #     article.delete()
    #     return redirect('webapp:index')

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from webapp.models import Comment, Article
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect
from webapp.forms import CommentForm


class CommentCreateView(LoginRequiredMixin, CreateView):
    template_name = 'comments/comment_create.html'
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.article = article
        comment.author = self.request.user
        comment.save()
        return redirect('webapp:article_view', pk=article.pk)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'comments/comment_update.html'
    model = Comment
    form_class = CommentForm
    permission_required = 'webapp.change_comment'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})


class CommentDeleteView(PermissionRequiredMixin, DeleteView):
    model = Comment
    permission_required = 'webapp.delete_comment'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

source/webapp/templates/article_create.html
{% extends 'base.html' %}

{% block title %}Create Article{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page"  href="{% url 'index' %}">На главную</a>{% endblock %}

{% block content %}
<h1>Create Article</h1>

<form action="" method="post">
    {% include 'partial/article_form.html' with value_submit='Create'  %}
</form>

{% endblock %}

source/webapp/templates/article_update.html
{% extends 'base.html' %}

{% block title %}Update Article{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page"  href="{% url 'index' %}">На главную</a>{% endblock %}

{% block content %}
<h1>Update Article</h1>

<form action="" method="post">
    {% include 'partial/article_form.html' with value_submit='Update' %}
</form>

{% endblock %}

source/webapp/templates/article_view.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock %}
{% block menu %}
    <a class="nav-link" aria-current="page" href="{% url 'index' %}">На главную</a>
    <a class="nav-link" aria-current="page" href="{% url 'article_update_view' pk=article.pk %}">Редактировать</a>
    <a class="nav-link" aria-current="page" href="{% url 'article_delete_view' pk=article.pk %}">Удалить</a>
{% endblock %}

{% block content %}
    <h1>Article</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ article.author }}</h6>
            <p class="card-text">{{ article.content }}</p>
            <p class="card-text">Tags: {% for tag in article.tags.all %}
                {{ tag.name }}{% if forloop.last %}.{% else %}, {% endif %}
            {% endfor %}
            </p>
            <p>{{ article.created_at }}</p>
        </div>
    </div>
    <h3 class="mt-2">Comments: </h3>
    <div class="row row-cols-3 mt-2">
        {% for comment in article.comments.all %}

            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Автор: {{ comment.author }}</h5>
                        <p class="card-text">{{ comment.text }}</p>
                        <p>{{ article.created_at }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Articles{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'webapp:index' %}">Articles</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
                {% block menu %}{% endblock %}

                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% get_language_info for LANGUAGE_CODE as current_language %}
                <div class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">{{ current_language.name_local }}</a>

                    <ul class="dropdown-menu">
                        {% for language in languages %}
                            <li><a class="dropdown-item {% if language.code == LANGUAGE_CODE %}active{% endif %}"
                                   href="/{{ language.code }}{{ language_base_link }}">
                                {{ language.name_local }} ({{ language.code }})
                            </a></li>

                        {% endfor %}

                    </ul>
                </div>
            </div>
            <div class="d-flex">
                {% if not request.user.is_authenticated %}
                    <a class="text-primary-emphasis text-decoration-none me-3" aria-current="page"
                       href="{% url 'accounts:user_create' %}?next={{ request.get_full_path }}">Регистрация</a>
                    <a class="text-success-emphasis text-decoration-none" aria-current="page"
                       href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Вход</a>
                {% else %}
                    <a href="{% url 'accounts:user_detail' request.user.id %}"
                       class="text-success me-3">{{ request.user }}</a>

                    <a class="text-success-emphasis text-decoration-none" aria-current="page"
                       href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выход</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

<script>
    async function makeRequest(url, method = 'GET', data = null, token = null) {
        let headers = {
            "Content-Type": "application/json"
        };
        if (token) {
            headers['Authorization'] = 'Token ' + token;

        }
        let options;

        if (method !== "GET") {
            options = {method, headers, body: JSON.stringify(data),};
        } else {
            options = {method, headers};
        }
        let response = await fetch(url, options);

        if (response.ok) {  // нормальный ответ
            return await response.json();
        } else {            // ошибка
            let error = new Error(response.statusText);
            error.response = response;
            throw error;
        }

    }

    async function onLoad() {
        let token = localStorage.getItem('apiToken');

        let response = await makeRequest('http://localhost:8000/api/v3/articles/comments-count/', "GET", null, token);
        console.log(response);
    }


    window.addEventListener('load', onLoad);


</script>

{% block script %}
{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}

{% block menu %}
    <a class="nav-link" aria-current="page" href="{% url 'article_create' %}">Создать статью</a>{% endblock %}

{% block content %}
    <h1>Articles</h1>

    <div class="row row-cols-3">

        {% for article in articles %}
            <div class="col">
                <div class="card my-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary">{{ article.author }}</h6>
                        <p class="card-text">{{ article.content }}</p>
                        <p class="card-text">Tags: {% for tag in article.tags.all %}
                            {{ tag.name }}{% if forloop.last %}.{% else %}, {% endif %}
                        {% endfor %}
                        </p>
                        <a href="{% url 'article_view' pk=article.pk %}" class="card-link">Подробнее...</a>
                        <a href="{% url 'article_update_view' pk=article.pk %}" class="card-link">Редактировать</a>
                        <a href="{% url 'article_delete_view' pk=article.pk %}" class="card-link">Удалить</a>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}